export const routes = {
  splash: '/(auth)/splash',
  login: '/(auth)/login',
  signup: '/(auth)/signup',
  home: '/(tabs)',
  records: '/(tabs)/records',
  medicines: '/(tabs)/medicines',
  chat: '/(tabs)/chat',
  profile: '/(tabs)/profile',
  appointments: '/appointment',
  bookAppointment: '/appointment/book',
  uploadPrescription: '/prescription/upload',
  history: '/history',
  reports: '/reports',
  search: '/search',
  notifications: '/notifications',
  dashboard: '/dashboard',
  emergency: '/emergency',
} as const;
